name: FastAPI CI/CD

on:
  push:
    branches:
      - main  # Adjust to your deployment branch

env:
  AWS_REGION: ap-southeast-1  
  ECR_REPOSITORY: fastapi-app
  CLUSTER_NAME: my-eks-cluster
  NAMESPACE: fastapi-namespace

permissions:
  contents: read

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run Tests
        run: PYTHONPATH=app pytest tests/

  build-and-deploy:
    name: Build & Deploy FastAPI
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $(aws ecr describe-repositories --query "repositories[?repositoryName=='${{ env.ECR_REPOSITORY }}'].repositoryUri" --output text)

      - name: Build and Push Docker Image
        run: |
          ECR_URI=$(aws ecr describe-repositories --query "repositories[?repositoryName=='${{ env.ECR_REPOSITORY }}'].repositoryUri" --output text)
          IMAGE_TAG=$(git rev-parse --short HEAD)
          docker build -t $ECR_URI:$IMAGE_TAG .
          docker tag $ECR_URI:$IMAGE_TAG $ECR_URI:latest
          docker push $ECR_URI:$IMAGE_TAG
          docker push $ECR_URI:latest

      - name: Update kubeconfig for AWS EKS
        run: aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME

      - name: Deploy to Kubernetes
        run: |
          ECR_URI=$(aws ecr describe-repositories --query "repositories[?repositoryName=='${{ env.ECR_REPOSITORY }}'].repositoryUri" --output text)
          IMAGE_TAG=$(git rev-parse --short HEAD)
          sed -i "s|<ECR_URI>|$ECR_URI|g" k8s/deployment.yaml
          sed -i "s|<IMAGE_TAG>|$IMAGE_TAG|g" k8s/deployment.yaml
          kubectl apply -f k8s/
